apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-deply
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      layer: frontend
      app: delivery-app
  template:
    metadata:
      name: menu-pod
      labels:
        layer: frontend
        app: delivery-app
    spec:
      containers:
      - name: menu-cont
        image: 339713063356.dkr.ecr.us-west-1.amazonaws.com/delivery-menu:v1.0.6
        ports:
        - name: web
          containerPort: 2011
          protocol: TCP
        resources:
          requests:
            memory: "200Mi"
            cpu: "2"
          limits:
            memory: "270Mi"
            cpu: "2"
