apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deply
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      layer: frontend
      app: delivery-app
  template:
    metadata:
      name: search-pod
      labels:
        layer: frontend
        app: delivery-app
    spec:
      containers:
      - name: search-cont
        image: ${{ env.IMAGE_NAME }}
        ports:
        - name: web
          containerPort: 2021
          protocol: TCP
        resources:
          requests:
            memory: "200Mi"
            cpu: "2"
          limits:
            memory: "270Mi"
            cpu: "2"
